name: felstorm integration test on push
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: felstorm integration test
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:

      - name: Get Spend Time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'